apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection-service
  labels:
    app: connection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connection-service
  template:
    metadata:
      labels:
        app: connection-service
    spec:
      containers:
      - name: connection-service
        image: connection-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: udaconnect-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udaconnect-db-secret
              key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: udaconnect-db-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: udaconnect-db-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: udaconnect-db-config
              key: name
---
apiVersion: v1
kind: Service
metadata:
  name: connection-service
spec:
  selector:
    app: connection-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
