apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-api
  labels:
    app: location-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-api
  template:
    metadata:
      labels:
        app: location-api
    spec:
      containers:
      - name: location-api
        image: location-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: location-api
spec:
  selector:
    app: location-api
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
