apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-consumer
  labels:
    app: location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-consumer
  template:
    metadata:
      labels:
        app: location-consumer
    spec:
      containers:
      - name: location-consumer
        image: location-consumer:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: udaconnect-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udaconnect-db-secret
              key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: udaconnect-db-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: udaconnect-db-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: udaconnect-db-config
              key: name
